---
title: "AI tongue twister contest - comparison of Text to Speech Systems."
draft: true
author: Shirin Glander
date: '2018-04-30'
categories: []
tags: []
thumbnailImagePosition: left
thumbnailImage: 
metaAlignment: center
coverMeta: out
slug: cc_tongue_twister_video
---

https://www.youtube.com/c/codecentricAI

Phishers Fritz phished frische Credentials,
Frische Credentials phished Fischers Fritz!

In diesem Video vergleichen wir aktuelle TTS bzw. Text to Speech Systeme mit Hilfe von Zungenbrechern. Wir veranstalten einen kleinen Wettbewerb zwischen Polly, Alexa, Siri und Co und hören uns einmal an, wie die aktuellen Systeme so klingen. Wir vergleichen deutsche und englische Stimmen/Modelle und versuchen auch selbst ein paar Zungenbrecher aufzusagen.

Mit Hilfe von neuronalen Netzen und Deep Learning sind Text to Speech Systeme in den vergangenen Jahren immer besser geworden. Heute gibt es Modelle, die schon sehr natürlich klingen und teilweise kaum noch von einem Menschen zu unterscheiden sind. 

Zusätzlich bieten die großen Cloud Anbieter wie Amazon, Google, IBM und Microsoft Text-to-Speech Systeme as a Service, so dass man mit wenig Aufwand Sprachausgabe in seine eigenen Programme integrieren kann. Auch diese Systeme hören wir uns kurz an.

<iframe width="560" height="315" src="https://www.youtube.com/embed/2EEMSsVBE8w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
