---
title: "codecentric.AI Thug Cat Project in R: keypoint regression with Keras"
draft: true
author: Shirin Glander
date: '2019-07-01'
categories: ["R", "codecentric.AI"]
tags: ["R", "codecentric.AI", "Keras", "TensorFlow"]
thumbnailImagePosition: left
thumbnailImage: 
metaAlignment: center
coverMeta: out
slug: thug_cat_r
---

https://bootcamp.codecentric.ai/

Module 5: Neural Nets and Deep Learning
Lesson 5.10: Thug Cat Project
https://bootcamp.codecentric.ai/dl-course/module/5/43/

## The data

```{r message = FALSE, warning=FALSE}
library(tidyverse)
path_to_images <- "/Users/shiringlander/Documents/Github/Data/cats/"
list_of_cat_images <- list.files(path_to_images, full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "*.jpg$")
list_of_cat_annos <- list.files(path_to_images, full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "*.cat$")

length(list_of_cat_images) == length(list_of_cat_annos)
length(list_of_cat_images)
head(list_of_cat_images)
```

```{r warning=FALSE, message=FALSE, eval=FALSE}
return_keypoints <- function(filename){
  pts <- gsub(".jpg", ".jpg.cat", filename)
  points <- read_delim(pts, delim = " ", col_names = keypoints) %>%
    slice(1) %>% 
    unlist(., use.names = TRUE)
  return(points)
}

mouth_label_x <- rep(NA, length(list_of_cat_images))
mouth_label_y <- rep(NA, length(list_of_cat_images))

for(i in 1:length(list_of_cat_images)) {
  img <- list_of_cat_images[i]
  kps_mouth <- return_keypoints(img)[6:7]
  
  mouth_label_x[i] <- kps_mouth[1]
  mouth_label_y[i] <- kps_mouth[2]
}

names(mouth_label_x) <- list_of_cat_images
names(mouth_label_y) <- list_of_cat_images
```

```{r}
flow_df <- data.frame(filepaths = list_of_cat_images,
                      mouth_label_x = mouth_label_x,
                      mouth_label_y = mouth_label_y)
saveRDS(flow_df, file = "/Users/shiringlander/Documents/Github/shirinsplayground/data/flow_df.rds")
```

```{r}
flow_df <- readRDS("/Users/shiringlander/Documents/Github/shirinsplayground/data/flow_df.rds")
head(flow_df)
dim(flow_df)
```

```{r}
library(keras)

imgdg <- image_data_generator(rescale = 1/255)

flow_imgdg_train <- flow_images_from_dataframe(dataframe = flow_df[1:8000, ],
                           class_mode = "other",
                           x_col = "filepaths",
                           #y_col = list("mouth_label_x", "mouth_label_y"),
                           y_col = "mouth_label_x",
                           generator = imgdg,
                           target_size = c(224, 224))

flow_imgdg_test <- flow_images_from_dataframe(dataframe = flow_df[8001:9997, ],
                           class_mode = "other",
                           x_col = "filepaths",
                           #y_col = list("mouth_label_x", "mouth_label_y"),
                           y_col = "mouth_label_x",
                           generator = imgdg,
                           target_size = c(224, 224))
```

```{r}
model_input <- layer_input(shape = c(224, 224, 3), dtype = 'float32', name = 'image_input')

predictions <- 
  model_input %>%
  layer_conv_2d(filter = 32, kernel_size = c(3,3), padding = "same") %>%
  layer_activation("relu") %>%

  layer_conv_2d(filter = 1, kernel_size = c(3,3), padding = "same") %>%
  layer_activation("relu") %>%
  
  layer_flatten() %>%
  layer_dense(10) %>%
  layer_activation("relu") %>%
  layer_dropout(0.5)

output_y1 <- 
  predictions %>%
  layer_dense(units = 1, activation = "linear", name = "output_y1")

output_y2 <-
  predictions %>%
  layer_dense(units = 1, activation = "linear", name = "output_y2")

model <- keras_model(
  inputs = model_input,
  #outputs = c(output_y1, output_y2)
  outputs = output_y1
)

model 
```

```{r}
model %>%
  compile(loss = 'mean_squared_error', # MSE for continuous output
          #loss_weights = c(0.5, 0.5), # Weight both coords equally 
          optimizer = optimizer_adam())
```

```{r}
history <- model %>% fit_generator(
    flow_imgdg_train,
    steps_per_epoch = 200,
    epochs = 3
)
```

```{r}
results <- model %>% 
  evaluate(x_test, list(y_test_lbl_x, y_test_lbl_y))
results
```

```{r}
coords_pred <- model %>% predict(image_test)
coords_pred
```

```{r}
image_test <- x_test[1, , , ]
image(image_test)
points(coords_pred[[1]], coords_pred[[2]])
```

