---
title: "US Roadtrip Location data mapping"
draft: true
author: Shirin Glander
date: '2018-03-27'
categories: [R]
tags: []
thumbnailImagePosition: left
thumbnailImage: 
metaAlignment: center
coverMeta: out
slug: roadtrip_2018
---

```{r echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE, eval=FALSE}
library(jsonlite)
system.time(x <- fromJSON("~/Documents/Github/Data/Takeout/Standortverlauf/Standortverlauf.json"))
```

```{r echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE, eval=FALSE}
# extracting the locations dataframe
loc = x$locations

# converting time column from posix milliseconds into a readable time scale
loc$time = as.POSIXct(as.numeric(x$locations$timestampMs)/1000, origin = "1970-01-01")

# converting longitude and latitude from E7 to GPS coordinates
loc$lat = loc$latitudeE7 / 1e7
loc$lon = loc$longitudeE7 / 1e7
```

```{r fig.width = 10, fig.height = 10, fig.align = "center", message=FALSE, warning=FALSE, eval=FALSE}
usa <- get_map(location = 'USA', zoom = 5)

```